# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dab_solver.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0_1/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0_1/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pl_ps_axi_0_12/design_1_pl_ps_axi_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pl_ps_axi_0_12 || ORIG_REF_NAME==design_1_pl_ps_axi_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dab_top_0_9/design_1_dab_top_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dab_top_0_9 || ORIG_REF_NAME==design_1_dab_top_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pwm_0_1/design_1_pwm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pwm_0_1 || ORIG_REF_NAME==design_1_pwm_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_7/design_1_system_ila_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_7 || ORIG_REF_NAME==design_1_system_ila_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: /home/dvd/SPL/spl_prj/spl_prj.gen/sources_1/bd/design_1/design_1_ooc.xdc
