#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 27 23:31:58 GMT 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim dab_tb_behav -key {Behavioral:sim_1:Functional:dab_tb} -tclbatch dab_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/dvd/SPL/spl_prj/spl_prj.srcs/sim_1/imports/dvd/SPL/spl_prj/solver_engine_tb_behav.wcfg -view /home/dvd/SPL/spl_prj/spl_prj.srcs/sim_1/imports/spl_prj/solver_engine_tb_behav1.wcfg -view /home/dvd/SPL/spl_prj/spl_prj.srcs/sim_1/imports/spl_prj/solver_engine_tb_behav2.wcfg -log simulate.log"
xsim dab_tb_behav -key {Behavioral:sim_1:Functional:dab_tb} -tclbatch dab_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/dvd/SPL/spl_prj/spl_prj.srcs/sim_1/imports/dvd/SPL/spl_prj/solver_engine_tb_behav.wcfg -view /home/dvd/SPL/spl_prj/spl_prj.srcs/sim_1/imports/spl_prj/solver_engine_tb_behav1.wcfg -view /home/dvd/SPL/spl_prj/spl_prj.srcs/sim_1/imports/spl_prj/solver_engine_tb_behav2.wcfg -log simulate.log

